name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build project and tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake graphviz
        
      - name: Install Google Test
        run: |
          sudo apt-get install -y libgtest-dev cmake
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Build end-to-end tests
        run: |
          mkdir -p test/end-to-end/build
          cd test/end-to-end/build
          cmake ..
          make

      - name: Build unit tests
        run: |
          mkdir -p test/unit-test/build
          cd test/unit-test/build
          cmake ..
          make

      - name: List build directory
        run: |
         ls -l test/unit-test/build

  end-to-end-tests:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
    
      - name: CheckDir
        run: |
          ls test/end-to-end

      - name: Run end-to-end tests
        run: |
          ./test/end-to-end/build/EndToEndTest 
 
      - name: Convert .dot to .png
        run: |
          dot -Tpng examples/tree.dot -o examples/tree.png

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
          ./test/unit-test/build/UnitTest
